### ISSUE TITLE
如何编译

### ISSUE THREAD

**Issue by kotori2** [xwang1024/SIF-Resource-Explorer#1]
求解下了源码和JavaFX以后要怎么把源码导入并编译。。_(:_」∠)_

**Comment by dgw** [comment]
English language repositories should get English language issues.

Google Translated:

> How to compile
> By solving the source and the source JavaFX how to import and compile later. .

**Comment by kotori2** [comment]
Well..How can I compile it into an .exe file?I have already downloaded JavaFX,but I don't know how to use it.

**Comment by dgw** [comment]
I haven't built it myself, but given the Maven settings files I'm going to guess that this will at least point you in the right direction: https://maven.apache.org/run-maven/

**Comment by kotori2** [comment]
You means I should use Maven to build it?_(:_」∠)_I'm a freshmen in Java.

**Comment by kotori2** [comment]
Now I built it by Maven and successfully get a .jar file.But it can't be execute at all!

**Comment by dgw** [comment]
You need the JRE (Java Runtime Environment) installed to run .jar files.

**Comment by kotori2** [comment]
I already installed it.But nothing was happened when I double click on it.And when I was using command line,many errors arose.

**Comment by kotori2** [comment]
I will be appreciated if you could send me the .jar file directly(_/ω＼_)

**Comment by dgw** [comment]
Maybe @xwang1024 would be willing to push up a compiled release?

As I said, I haven't built or used this project myself yet; I'm just following it.

**Comment by xwang1024** [comment]
@lijun0326 I have uploaded a runnable jar file to 'release' section

**Comment by xwang1024** [comment]
@lijun0326 But firstly, you need to ensure your game assets folder has been decrypted...
